name: Create Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Marp CLI Action
        uses: KoharaKazuya/marp-cli-action@v2.0.0
